### ISSUE TITLE
EMPACOTAMENTO DA VERSAO 4.00 DO SPED FISCAL

### ISSUE THREAD

**Issue by suportesig42** [cpuhouse/sped-rfb#1]
Nova versao do sped fiscal 4.00, precisamos que as maquinas do suporte tenha sped fiscal atualizados para versao 4.0.0.

**Comment by christiantosta** [comment]
Bom dia. Infelizmente o link do site da RFB de onde baixamos a versão está indisponível:

![image](https://github.com/cpuhouse/sped-rfb/assets/7252968/379bf4d5-183d-4f6f-9847-dc6e96974992)

Iremos atualizar assim que o acesso for normalizado.

**Comment by christiantosta** [comment]
Resolvido no commit 6d2da36.
